version: 2

jobs:
  gcc-8:
    docker:
      - image: lyrahgames/gcc-build2:8-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            cd tests
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  gcc-9:
    docker:
      - image: lyrahgames/gcc-build2:9-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            cd tests
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  gcc-10:
    docker:
      - image: lyrahgames/gcc-build2:10-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            cd tests
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  clang-9:
    docker:
      - image: lyrahgames/clang-build2:9-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            cd tests
            bdep init -C @clang cc config.cxx=clang++
            b test: tests/

  clang-10:
    docker:
      - image: lyrahgames/clang-build2:10-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            cd tests
            bdep init -C @clang cc config.cxx=clang++
            b test: tests/

  # coverage:
  #   docker:
  #     - image: lyrahgames/gcc-build2:10-0.13
  #   steps:
  #     - checkout
  #     - run:
  #         name: build2_configure_build_test
  #         command: |
  #           apt update && apt install -y kcov
  #           cd tests
  #           bdep init -C @coverage cc config.cxx=g++ "config.cxx.coptions=-g -O0 -fprofile-arcs -ftest-coverage" "config.cxx.loptions=-fprofile-arcs -ftest-coverage"
  #           b
  #           kcov --include-path=lyrahgames/lyrahgames,../project-coverage/lyrahgames/lyrahgames ../coverage tests/tests/tests
  #           bash <(curl -s https://codecov.io/bash) -s ../coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-8
      - gcc-9
      - gcc-10
      - clang-9
      - clang-10
      # - coverage