version: 2

jobs:
  gcc-8:
    docker:
      - image: lyrahgames/gcc-build2:8-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  gcc-9:
    docker:
      - image: lyrahgames/gcc-build2:9-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  gcc-10:
    docker:
      - image: lyrahgames/gcc-build2:10-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            bdep init -C @gcc cc config.cxx=g++
            b test: tests/

  clang-9:
    docker:
      - image: lyrahgames/clang-build2:9-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            bdep init -C @clang cc config.cxx=clang++
            b test: tests/

  clang-10:
    docker:
      - image: lyrahgames/clang-build2:10-0.13
    steps:
      - checkout
      - run:
          name: build2_configure_build_test
          command: |
            bdep init -C @clang cc config.cxx=clang++
            b test: tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-8
      - gcc-9
      - gcc-10
      - clang-9
      - clang-10